version: '3.9'

services:

  db_dzencode:
    container_name: db_dzencode
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080