# Generated by Django 5.0.3 on 2024-05-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('homepage', models.URLField(blank=True)),
                ('text', models.TextField()),
                ('commentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments_app.comment')),
            ],
        ),
    ]
