# Generated by Django 5.0.3 on 2024-05-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0003_comment_parent_comment_delete_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='child_comment',
        ),
    ]
