# Generated by Django 5.0.3 on 2024-05-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='child_comment',
            new_name='parent_comment',
        ),
    ]
