# Generated by Django 5.0.3 on 2024-05-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0008_rename_parent_comment_comment_parent_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment_id',
            new_name='parent_comment',
        ),
    ]
