# Generated by Django 5.0.3 on 2024-05-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0009_rename_parent_comment_id_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
