# Generated by Django 5.0.3 on 2024-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0012_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_files/'),
        ),
    ]
